name: E2E Tests

on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install

    - name: Run E2E Tests
      run: |
        npx cypress run --config video=false
